"""Corrected col name user_id to user_uid and book_id to book_uid in Reviews table

Revision ID: 7740de5c0ac4
Revises: dc08c4159dfc
Create Date: 2026-04-22 18:53:35.595984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7740de5c0ac4'
down_revision: Union[str, Sequence[str], None] = 'dc08c4159dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.add_column('reviews', sa.Column('book_uid', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_reviews_book_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_book_uid'), 'reviews', ['book_uid'], unique=False)
    op.create_index(op.f('ix_reviews_user_uid'), 'reviews', ['user_uid'], unique=False)
    op.drop_constraint(op.f('reviews_book_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['uid'])
    op.create_foreign_key(op.f('reviews_book_id_fkey'), 'reviews', 'books', ['book_id'], ['uid'])
    op.drop_index(op.f('ix_reviews_user_uid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_book_uid'), table_name='reviews')
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_book_id'), 'reviews', ['book_id'], unique=False)
    op.drop_column('reviews', 'book_uid')
    op.drop_column('reviews', 'user_uid')
    # ### end Alembic commands ###
